db:
  image: mdillon/postgis:9.3
  volumes:
    - ./postgres_data:/var/lib/postgresql
  ports:
    - "5433:5432"
web:
  build: ./web/
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - ./web/:/code
  ports:
    - "8000:8000"
  links:
    - db
